config/routes.rb
Erira::Application.routes.draw do

  get "user_settings/edit"

  get "sessions/new"

  get "register/signup"

  namespace :admin do
    resources :users do
      post :unlock, :on => :member
      post :lock, :on => :member
    end
    resources :nodes
    resources :audits
    resources :konfigs
    resources :rights
    resources :roles
    resources :features do
      get 'refresh', :on => :collection
      get 'enable', :on => :member
      get 'disable', :on => :member
    end

  end
  resources :filters
  resources :jobs

  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_settings, :only => [:edit, :update]
  resources :microposts, :only => [:create, :destroy]

  match '/signup', :to => 'public/register#signup'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/chgpswd', :to => 'sessions#change_password', :via => :get
  match '/chgpswd' => 'sessions#update_password', :via => :put

  match '/home', :to => 'home#index'

  match '/about', :to => 'public/help#about'
  match '/launchpad', :to => 'home#launchpad'
  match '/help', :to => 'public/help#help'

  root :to => 'home#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :name, :right_ids
  #attr_accessor :right_ids

  has_many :permissions, :dependent => :destroy
  has_many :user_roles, :dependent => :destroy
  has_many :users, :through => :user_roles
  has_many :rights, :through =>  :permissions

end

app/models/user.rb
require 'digest'

#class UserCache
#  attr_accessor :id, :email, :roles, :rights, :applets
#
#  def initialize( id, email, roles, rights, apps )
#    self.id = id
#    self.email = email
#    self.roles = roles
#    self.rights = rights
#    self.applets = apps
#  end
#
#end


class User < ActiveRecord::Base
  attr_accessible :email, :name, :pswd, :password, :password_confirmation
  attr_accessor :password
  attr_protected :expiry, :lock, :account_expiry, :failed

  #class << self; attr_accessor :users end

  #after_save :upd_usr
  #after_destroy :dest_usr

  has_many :microposts #, :dependent => :destroy
  has_many :jobs, :foreign_key => 'userId'
  has_many :user_roles, :dependent => :destroy
  has_many :roles, :through => :user_roles
  has_many :rights, :through => :roles
  has_many :applets, :through => :rights

  before_save :encrypt_password

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
            :length => { :maximum => 50 }

  validates :email, :presence => true,
            :format => { :with => email_regex },
            :uniqueness => { :case_sensitive => false }

  validates :password, :presence => true, :on => :create,
            :confirmation => true,
            :length => { :within => 6..40 }

  validates :password, :presence => true, :on => :update, :if => Proc.new { |user| !user.password.blank? },
            :confirmation => true,
            :length => { :within => 6..40 }



  def has_password?( submitted_password )
    # Compare encrypted_password with the encrypted version of
    # submitted_password.
    pswd == "omtv1" + encrypt( submitted_password )
  end

  def self.authenticate( email, submitted_password )
    #user = find_by_email(email) #changed to support case-insensitive email
    user = User.first( :conditions => [ "lower(email) = ?", email.downcase ] )
    return nil if user.nil?
    return user.clearLoginFailed if user.has_password?( submitted_password ) else user.loginFailed
  end

  def self.authenticate_with_salt( id, cookie_salt )
    user = find_by_id( id )
    ( user && user.salt == cookie_salt && !user.lock ) ? user : nil
  end

  # Increase failed counter and lock account id cross threshold
  def loginFailed
    self.failed += 1
    # bypass if konfig is zero, means no fail checking
    if Konfig::KONFIGS[ :allowedFailedLogin ] != 0 && self.failed > Konfig::KONFIGS[ :allowedFailedLogin ]
      self.lock = true
    end
    self.save!
    return nil
  end

  # Clear (set to 0) failed counter on first successful login
  # Do not anything to lock, admin should unlock it
  def clearLoginFailed
    self.failed = 0
    if self.changed?
      self.save!
    end
    return self
  end

  #def self.init
  #  puts 'Initing User'
  #  User.users = Hash.new
  #  User.all.each { |u| @users[u.id] = UserCache.new( u.id, u.email, u.roles, u.rights, u.applets ) }
  #  User.users.each { |user| user.inspect }
  #end

  private
    def encrypt_password
      if !password.blank?
        self.salt = "omtv1" + make_salt # if new_record?
        self.pswd = "omtv1" + encrypt( password )
      end
    end

    def encrypt( string )
      secure_hash( "#{salt}--Omid--#{string}" )
    end

    def make_salt
      secure_hash( "#{Time.now.utc}--Omid--#{password}" )
    end

    def secure_hash( string )
      Digest::SHA2.hexdigest( string )
    end


    # User model cache update methods
  #  def upd_usr
  #    puts 'update user'
  #    @users[ self.id ] = UserCache.new( u.id, u.email, u.roles, u.rights, u.applets )
  #  end
  #
  #  def dest_usr
  #    puts 'delete user'
  #    @users.delete( self.id )
  #  end
  #
  #User.init

end
#

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Backend::SecureController
  # GET /admin/roles
  # GET /admin/roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /admin/roles/1
  # GET /admin/roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /admin/roles/new
  # GET /admin/roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /admin/roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /admin/roles
  # POST /admin/roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to admin_role_path(@role), notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: admin_role_path(@role) }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/roles/1
  # PUT /admin/roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to admin_role_path(@role), notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/roles/1
  # DELETE /admin/roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to admin_roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/views/admin/roles/_form.html.erb
<%= form_for [:admin, @role] do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, :class => "focused"%>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>

    <div class="field">
      <%= f.label :rights %><br />
      <%= f.select(:right_ids, Right.all(:order=>"controller, action ASC").collect { |x| ["#{x.controller} #{x.action}" , x.id]}, {}, :multiple => true)%>
    </div>


    <div class="actions">
    <%= f.submit :class => 'minibutton'%>
    <br/><br/>
  </div>
<% end %>

app/views/admin/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>
<br/>
<div class='button-group'>
<%= link_to 'Show', admin_role_path(@role), :class => 'minibutton' %>
<%= link_to 'Delete', admin_role_path(@role), method: :delete, data: { confirm: 'Are you sure you want to delete this role ? It removes permission of all users in this role.' }, :class => 'minibutton' %>
<%= link_to 'Back', admin_roles_path, :class => 'minibutton' %>
</div>

app/views/admin/roles/index.html.erb
<h1>Roles</h1>
<%= link_to 'New Role', new_admin_role_path, :class => 'minibutton' %>
<br/>
<br/>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= link_to role.name, admin_role_path(role) %></td>
    <td><%= link_to role.description, admin_role_path(role) %></td>
    <td><%= link_to 'x', admin_role_path(role), method: :delete, data: { confirm: 'Are you sure you want to delete this role ? It removes permission of all users in this role.' } %></td>
  </tr>
<% end %>
</table>
<br/>
<%= link_to 'New Role', new_admin_role_path, :class => 'minibutton' %>

app/views/admin/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_roles_path, :class => 'minibutton' %>

app/views/admin/roles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="span-3 colborder">
  <label>Name</label><br>
  <%= @role.name%>
</div>

<div class="span-3 colborder">
  <label>Description</label><br>
  <%= @role.description%>
</div>

<div class="span-3 last">
  <label>Rights</label><br>
  <%= select(@role, :right_ids, Right.all(:order=>"controller, action ASC").collect { |x| ["#{x.controller} #{x.action}" , x.id]}, {:selected => @role.right_ids}, {:multiple => true, :disabled => true}) %>
</div>

<br/>
<hr>

<div class='button-group'>
<%= link_to 'Edit', edit_admin_role_path(@role), :class => 'minibutton' %>
<%= link_to 'Delete', admin_role_path(@role), method: :delete, data: { confirm: 'Are you sure you want to delete this role ? It removes permission of all users in this role.' }, :class => 'minibutton' %>
<%= link_to 'Back', admin_roles_path, :class => 'minibutton' %>
</div>