config/routes.rb
Erira::Application.routes.draw do

  get "user_settings/edit"

  get "sessions/new"

  get "register/signup"

  namespace :admin do
    resources :users do
      post :unlock, :on => :member
      post :lock, :on => :member
    end
    resources :nodes
    resources :audits
    resources :konfigs
    resources :rights
    resources :roles
    resources :features do
      get 'refresh', :on => :collection
      get 'enable', :on => :member
      get 'disable', :on => :member
    end

  end
  resources :filters
  resources :jobs

  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_settings, :only => [:edit, :update]
  resources :microposts, :only => [:create, :destroy]

  match '/signup', :to => 'public/register#signup'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/chgpswd', :to => 'sessions#change_password', :via => :get
  match '/chgpswd' => 'sessions#update_password', :via => :put

  match '/home', :to => 'home#index'

  match '/about', :to => 'public/help#about'
  match '/launchpad', :to => 'home#launchpad'
  match '/help', :to => 'public/help#help'

  root :to => 'home#index'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content  #, :msisdn_id

  belongs_to :user
  #belongs_to :subscriber, :foreign_key => 'msisdn_id'

  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true

  default_scope :order => 'microposts.created_at DESC'

end

app/controllers/microposts_controller.rb
class MicropostsController < Backend::SecureController

  # POST /microposts
  # POST /microposts.json
  def create
    begin
    @micropost = current_user.microposts.build(params[:micropost])

    if @micropost.save
      flash[:success] = "Micropost created!"
      flash[:error] = 'Error'
      #redirect_to home_path
    else
      #render home_path
      flash[:error] = 'Error'
    end

    rescue => err
      flash[:error] = err
    end

    redirect_to home2_path, :error => 'Error'

    #respond_to do |format|
    #  if @micropost.save
    #    format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
    #    format.json { render json: @micropost, status: :created, location: @micropost }
    #  else
    #    format.html { render action: "new" }
    #    format.json { render json: @micropost.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit :class => 'minibutton' %>
    <br/><br/>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="subscriber">
      <%= "MSISDN: #{micropost.subscriber.msisdn}" unless !micropost.subscriber %>
    </span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
</tr>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<div class='button-group'>
<%= link_to 'Show', @micropost, :class => 'minibutton'%>
<%= link_to 'Back', microposts_path, :class => 'minibutton' %>
</div>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= link_to 'Show', micropost, :class => 'minibutton' %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost), :class => 'minibutton' %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'minibutton' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path, :class => 'minibutton' %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<div class='button-group'>
<%= link_to 'Edit', edit_micropost_path(@micropost), :class => 'minibutton' %>
<%= link_to 'Back', microposts_path, :class => 'minibutton' %>
</div>