config/routes.rb
Erira::Application.routes.draw do

  get "user_settings/edit"

  get "sessions/new"

  get "register/signup"

  namespace :admin do
    resources :users do
      post :unlock, :on => :member
      post :lock, :on => :member
    end
    resources :nodes
    resources :audits
    resources :konfigs
    resources :rights
    resources :roles
    resources :features do
      get 'refresh', :on => :collection
      get 'enable', :on => :member
      get 'disable', :on => :member
    end

  end
  resources :filters
  resources :jobs

  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_settings, :only => [:edit, :update]
  resources :microposts, :only => [:create, :destroy]

  match '/signup', :to => 'public/register#signup'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/chgpswd', :to => 'sessions#change_password', :via => :get
  match '/chgpswd' => 'sessions#update_password', :via => :put

  match '/home', :to => 'home#index'

  match '/about', :to => 'public/help#about'
  match '/launchpad', :to => 'home#launchpad'
  match '/help', :to => 'public/help#help'

  root :to => 'home#index'

end

app/models/filter.rb
class Filter < ActiveRecord::Base
  attr_accessible :group, :name, :pattern
end

app/controllers/filters_controller.rb
class FiltersController < Backend::SecureController
  # GET /filters
  # GET /filters.json
  def index
    @filters = Filter.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @filters }
    end
  end

  # GET /filters/1
  # GET /filters/1.json
  def show
    @filter = Filter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @filter }
    end
  end

  # GET /filters/new
  # GET /filters/new.json
  def new
    @filter = Filter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @filter }
    end
  end

  # GET /filters/1/edit
  def edit
    @filter = Filter.find(params[:id])
  end

  # POST /filters
  # POST /filters.json
  def create
    @filter = Filter.find_or_create_by_name( params[:filter][:name], :group => params[:filter][:group], :pattern => params[:filter][:pattern] )

    Auditlog( self.class.name, @filter )

    respond_to do |format|
      if @filter
        format.html { redirect_to @filter, notice: 'Filter was successfully created.' }
        format.json { render json: @filter, status: :created, location: @filter }
      else
        format.html { render action: "new" }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /filters/1
  # PUT /filters/1.json
  def update
    @filter = Filter.find(params[:id])

    Auditlog( self.class.name, @filter )

    respond_to do |format|
      if @filter.update_attributes(params[:filter])
        format.html { redirect_to @filter, notice: 'Filter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filters/1
  # DELETE /filters/1.json
  def destroy
    if params[:id] != '-1'
      @filter = Filter.find(params[:id])
    else
      @filter = Filter.where( :name => params[:filter][:name], :group => params[:filter][:group], :pattern => params[:filter][:pattern] ).first
    end

    Auditlog( self.class.name, @filter )

    if @filter
      @filter.destroy
    end

    respond_to do |format|
      format.html { redirect_to filters_url }
      format.json { head :no_content }
    end
  end
end

app/views/filters/_form.html.erb
<%= form_for(@filter) do |f| %>
  <% if @filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

      <ul>
      <% @filter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :group %><br />
      <%= f.text_field :group %>
    </div>
    <div class="field">
      <%= f.label :pattern %><br />
      <%= f.text_field :pattern %>
    </div>
    <div class="actions">
    <%= f.submit :class => 'minibutton' %>
    </div>
<% end %>

app/views/filters/edit.html.erb
<h1>Editing filter</h1>

<%= render 'form' %>
<br/>
<div class='button-group'>
<%= link_to 'Show', @filter, :class => 'minibutton' %>
<%= link_to 'Back', filters_path, :class => 'minibutton' %>
</div>

app/views/filters/index.html.erb
<h1>Filters</h1>

<%= link_to 'New Filter', new_filter_path, :class => 'minibutton' %>
<br/><br/>
<%= will_paginate %>
<table>
  <tr>
    <th>Name</th>
    <th>Group</th>
    <th>Pattern</th>
    <!--<th></th>-->
    <th></th>
  </tr>

<% @filters.each do |filter| %>
  <tr>
    <td><%= link_to filter.name, filter %></td>
    <td><%= link_to filter.group, filter %></td>
    <td><%= link_to filter.pattern, filter %></td>
    <!--<td><%= link_to 'Edit', edit_filter_path(filter), :class => 'minibutton' %></td>-->
    <td><%= link_to 'x', filter, method: :delete, data: { confirm: 'Are you sure to remove?' }, :class => 'minibutton' %></td>
  </tr>
<% end %>
</table>

<br />

<%= will_paginate %>
<%= link_to 'New Filter', new_filter_path, :class => 'minibutton' %>

app/views/filters/new.html.erb
<h1>New Filter</h1>

<%= link_to 'Back', filters_path, :class => 'minibutton' %>
<br/><br/>
<%= render 'form' %>

app/views/filters/show.html.erb
<p id="notice"><%= notice %></p>

<div class="">
  <Strong>Name</Strong></Strong><br />
  <%= @filter.name %>
</div>
<br/>
<div class="">
  <Strong>Group</Strong><br />
  <%= @filter.group %>
</div>
<br/>
<div class="">
  <Strong>Pattern</Strong><br />
  <%= @filter.pattern %>
</div>
<br/>

<div class='button-group'>
<%= link_to 'Edit', edit_filter_path(@filter), :class => 'minibutton' %>
<%= link_to 'Back', filters_path, :class => 'minibutton' %>
</div>