config/routes.rb
Erira::Application.routes.draw do

  get "user_settings/edit"

  get "sessions/new"

  get "register/signup"

  namespace :admin do
    resources :users do
      post :unlock, :on => :member
      post :lock, :on => :member
    end
    resources :nodes
    resources :audits
    resources :konfigs
    resources :rights
    resources :roles
    resources :features do
      get 'refresh', :on => :collection
      get 'enable', :on => :member
      get 'disable', :on => :member
    end

  end
  resources :filters
  resources :jobs

  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_settings, :only => [:edit, :update]
  resources :microposts, :only => [:create, :destroy]

  match '/signup', :to => 'public/register#signup'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/chgpswd', :to => 'sessions#change_password', :via => :get
  match '/chgpswd' => 'sessions#update_password', :via => :put

  match '/home', :to => 'home#index'

  match '/about', :to => 'public/help#about'
  match '/launchpad', :to => 'home#launchpad'
  match '/help', :to => 'public/help#help'

  root :to => 'home#index'

end

app/models/user.rb
require 'digest'

#class UserCache
#  attr_accessor :id, :email, :roles, :rights, :applets
#
#  def initialize( id, email, roles, rights, apps )
#    self.id = id
#    self.email = email
#    self.roles = roles
#    self.rights = rights
#    self.applets = apps
#  end
#
#end


class User < ActiveRecord::Base
  attr_accessible :email, :name, :pswd, :password, :password_confirmation
  attr_accessor :password
  attr_protected :expiry, :lock, :account_expiry, :failed

  #class << self; attr_accessor :users end

  #after_save :upd_usr
  #after_destroy :dest_usr

  has_many :microposts #, :dependent => :destroy
  has_many :jobs, :foreign_key => 'userId'
  has_many :user_roles, :dependent => :destroy
  has_many :roles, :through => :user_roles
  has_many :rights, :through => :roles
  has_many :applets, :through => :rights

  before_save :encrypt_password

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
            :length => { :maximum => 50 }

  validates :email, :presence => true,
            :format => { :with => email_regex },
            :uniqueness => { :case_sensitive => false }

  validates :password, :presence => true, :on => :create,
            :confirmation => true,
            :length => { :within => 6..40 }

  validates :password, :presence => true, :on => :update, :if => Proc.new { |user| !user.password.blank? },
            :confirmation => true,
            :length => { :within => 6..40 }



  def has_password?( submitted_password )
    # Compare encrypted_password with the encrypted version of
    # submitted_password.
    pswd == "omtv1" + encrypt( submitted_password )
  end

  def self.authenticate( email, submitted_password )
    #user = find_by_email(email) #changed to support case-insensitive email
    user = User.first( :conditions => [ "lower(email) = ?", email.downcase ] )
    return nil if user.nil?
    return user.clearLoginFailed if user.has_password?( submitted_password ) else user.loginFailed
  end

  def self.authenticate_with_salt( id, cookie_salt )
    user = find_by_id( id )
    ( user && user.salt == cookie_salt && !user.lock ) ? user : nil
  end

  # Increase failed counter and lock account id cross threshold
  def loginFailed
    self.failed += 1
    # bypass if konfig is zero, means no fail checking
    if Konfig::KONFIGS[ :allowedFailedLogin ] != 0 && self.failed > Konfig::KONFIGS[ :allowedFailedLogin ]
      self.lock = true
    end
    self.save!
    return nil
  end

  # Clear (set to 0) failed counter on first successful login
  # Do not anything to lock, admin should unlock it
  def clearLoginFailed
    self.failed = 0
    if self.changed?
      self.save!
    end
    return self
  end

  #def self.init
  #  puts 'Initing User'
  #  User.users = Hash.new
  #  User.all.each { |u| @users[u.id] = UserCache.new( u.id, u.email, u.roles, u.rights, u.applets ) }
  #  User.users.each { |user| user.inspect }
  #end

  private
    def encrypt_password
      if !password.blank?
        self.salt = "omtv1" + make_salt # if new_record?
        self.pswd = "omtv1" + encrypt( password )
      end
    end

    def encrypt( string )
      secure_hash( "#{salt}--Omid--#{string}" )
    end

    def make_salt
      secure_hash( "#{Time.now.utc}--Omid--#{password}" )
    end

    def secure_hash( string )
      Digest::SHA2.hexdigest( string )
    end


    # User model cache update methods
  #  def upd_usr
  #    puts 'update user'
  #    @users[ self.id ] = UserCache.new( u.id, u.email, u.roles, u.rights, u.applets )
  #  end
  #
  #  def dest_usr
  #    puts 'delete user'
  #    @users.delete( self.id )
  #  end
  #
  #User.init

end
#

app/controllers/admin/users_controller.rb
require 'tasks/welcome_mail_task'

class Admin::UsersController < Backend::SecureController

  #before_filter :admin_user, :only => :destroy
  #include Util

  def index
    @title = "All Users"
    #@users = User.all
    @users = User.paginate(:page => params[:page])
    store_location
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.name + " Profile"
  end

  def new
    @user = User.new
    @title = "New User"
  end

  def create
    @user = User.new()
    @user.name = params[ :user ][ :name ]
    @user.email = params[ :user ][ :email ]
    @user.password = params[ :user ][ :password ]
    @user.password_confirmation = params[ :user ][ :password_confirmation ]
    @user.expiry = params[ :user ][ :expiry ]
    @user.account_expiry = params[ :user ][ :account_expiry ]
    @user.lock = params[ :user ][ :lock ]
    @user.roles = Role.where( :id => params[ :user ][ :role_ids ] )

    if @user.save
      # It is not the case where admin has to confirm registration
      # sign_in @user
      Applog.info "New user is added #{@user.name} [#{@user.email}]]"
      flash[:success] = "User #{@user.email} is added to ///RIRA"

      # Add mailing process to background process
      Job.enqueue( :task => WelcomeMailTask.new( @user ),
                   :name => 'Welcome Email',
                   :userId => current_user.id,
                   :queue => Job::MAIL_DELIVERY_QUEUE,
                   :message => 'Waiting to deliver' )
      redirect_to admin_user_path(@user)
    else
      @title = "New User"
      render 'new'
    end

    Auditlog( self.class.name, @user )

  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:success] = "User [#{user.name}] deleted."
    Applog.info "User #{user.name} [#{user.email}] deleted ]"
    Auditlog( self.class.name, user )
    redirect_to admin_users_path
  end

  def unlock
    user = User.find( params[ :id ] )
    user.update_attribute( :lock, false )
    user.update_attribute( :failed, 0 )
    Applog.info "User #{user.name} [#{user.email}] unloked"
    Auditlog( self.class.name, user )
    redirect_back_or admin_users_path
  end

  def lock
    user = User.find( params[ :id ] )
    user.update_attribute( :lock, true )
    Applog.info "User #{user.name} [#{user.email}] loked"
    Auditlog( self.class.name, user )
    redirect_back_or admin_users_path
  end

  def edit
    if @user.nil?
      @user = User.find( params[ :id ] )
    end
    @title = "Edit user #{@user.email}"
    @microposts = @user.microposts.paginate( :page => params[ :page ] )
    store_location
  end

  def update
    @user = User.find( params[ :id ] )

    #puts params[ :user ]

    @title = "Edit user #{@user.email}"
    @user.email = params[ :user ][ :email ]
    @user.name = params[ :user ][ :name ]
    @user.expiry = params[ :user ][ :expiry ]
    @user.account_expiry = params[ :user ][ :account_expiry ]
    @user.roles = Role.where( :id => params[ :user ][ :role_ids ] )


    if !params[ :user ][ :password ].nil? && !params[ :user ][ :password ].blank?
      @user.password = params[ :user ][ :password ]
      @user.password_confirmation = params[ :user ][ :password_confirmation ]
      if @user.save( :validate => true )
        Applog.info "User #{@user.name} [#{@user.email}] properties updated, include password"
        flash[:success] = "User settings updated [Password has been changed]"
      else
        render :edit
        return
      end
    else
      if @user.save( :validate => true )
        Applog.info "User #{@user.name} [#{@user.email}] properties updated"
        flash[:success] = "User settings updated."
      else
        render :edit
        return
      end
    end
    Auditlog( self.class.name, @user )
    redirect_back_or admin_users_path
    #render :edit
  end

end

app/views/admin/users/edit.html.erb
<h2>Account information of<br> <%=@user.email%></h2>

<%= form_for(@user, :url => admin_user_path) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>

  <table class="profile" summary="User Profile Information">
  <tr>
    <td class="main">

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %><br /> <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="field">
      <%= f.label :roles %><br />
      <%= f.select(:role_ids, Role.all(:order=>"name ASC").collect { |x| [x.name , x.id]}, {}, :multiple => true)%>
    </div>

    <div class="actions">
      <%= f.submit "Update", :class => 'minibutton'%>
    </div>
    </td>

    <!--Sidebar-->

    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %> <div style="font-size: 0.75em"> <%= @user.lock ? "[LOCKED]" : "" %></div>
      <div>
        <strong><%= link_to "Microposts #{@user.microposts.count}", admin_user_path(@user) %></strong>
      </div>
      <div class="field">
        <%= f.label :password_expiry %><br />
        <%= f.text_field :expiry, :class => "datepicker", :value => formatDate( @user.expiry ) %>
      </div>
      <div class="field">
        <%= f.label :account_expiry %><br />
        <%= f.text_field :account_expiry, :class => 'datepicker', :value => formatDate( @user.account_expiry ) %>
      </div>
      <div class="field">
        <%= link_to @user.lock ? "✓ Unlock" : "- Lock", @user.lock ? unlock_admin_user_path(@user) : lock_admin_user_path(@user),
                    :method  => "#{@user.lock ? "un": "" }lock",
                    :data => { :confirm => "Are you sure to #{@user.lock ? "un": "" }lock #{@user.name} ?", :title => "#{@user.lock ? "un": "" }lock #{@user.email}"}, :class => 'minibutton' %>
        <br/>
        <br/>
        <%= link_to "x Delete", admin_user_path(@user), :method => :delete,
                    :data => { :confirm => "Are you sure to delete #{@user.name} ?",
                               :title => "Delete #{@user.email}" }, :class => 'minibutton' %>
      </div>
      <br/>
      <div class='button-group'>
      <%= link_to 'View', admin_user_path(@user), :class => 'minibutton' %>
      <%= link_to 'User List', admin_users_path, :class => 'minibutton' %>
      </div>
    </td>
  </tr>
</table>

<% end %>

app/views/admin/users/index.html.erb
<h1>All Users</h1>

<%= link_to 'New User', new_admin_user_path, :class => 'minibutton' %>
<br/>
<br/>
<%= will_paginate %>
<table class="usersTable">
  <thead>
    <tr>
      <td>email</td>
      <td>Name</td>
      <td></td>
      <td>Password Expiry</td>
      <td>Lock</td>
      <td>Delete</td>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
      <td><%= link_to user.email, edit_admin_user_path(user) %></td>
      <td><%= user.name %></td>
      <td><%=  %></td>
      <td><%= formatDate user.expiry %></td>
      <td class="center"><%= link_to user.lock ? "✓" : "-", user.lock ? unlock_admin_user_path(user) : lock_admin_user_path(user),
                      :method  => "#{user.lock ? "un": "" }lock",
                      :data => { :confirm => "Are you sure to #{user.lock ? "un": "" }lock #{user.name} ?", :title => "#{user.lock ? "un": "" }lock #{user.email}"}, :class => 'minibutton' %></td>
      <td class="center"><%= link_to "x", admin_user_path(user), :method => :delete,
                      :data => { :confirm => "Are you sure to delete #{user.name} ?",
                                   :title => "Delete #{user.email}" }, :class => 'minibutton' %></td>
    </tr>
  <% end %>
  </tbody>
  </table>

<%= will_paginate %>

app/views/admin/users/new.html.erb
<h3>Creating New User</h3>
<%= link_to 'Users List', admin_users_path, :class => 'minibutton' %>
<br/><br/>
<%= form_for(@user, :url => admin_users_path ) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.text_field :email %>
          </div>
          <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password %>
          </div>
    <div class="field">
            <%= f.label :password_confirmation, "Confirmation" %><br/>
            <%= f.password_field :password_confirmation %>
          </div>
          <div class="field">
            <%= f.label :password_expiry %><br />
            <%= f.text_field :expiry, :class => 'datepicker' %>
          </div>
          <div class="field">
            <%= f.label :account_expiry %><br />
            <%= f.text_field :account_expiry, :class => 'datepicker' %>
          </div>
          <div class="field">
            <%= f.label :lock %><br />
            <%= f.check_box :lock %>
          </div>
          <div class="field">
            <%= f.label :roles %><br />
            <%= f.select(:role_ids, Role.all(:order=>"name ASC").collect { |x| [x.name , x.id]}, {}, :multiple => true)%>
          </div>
    <div class="actions">
        <br /><%= f.submit "Create User", :class => 'minibutton' %>
    </div>
<% end %>

app/views/admin/users/show.html.erb
<table class="profile" summary="User Profile information">
  <tr>
      <td class="main">
          <h3>
            <%= "#{@user.email}" %>
          </h3>
        <% unless @user.microposts.empty? %>
            <%= will_paginate @microposts %>
            <table class="microposts" summary="User microposts">
              <%= render :collection => @microposts, :partial => 'microposts/micropost' %>
            </table>
            <%= will_paginate @microposts %>
        <% end %>

      </td>
      <td class="sidebar round">
        <strong>Name</strong> <%= @user.name %><br />
        <div style="font-size: 0.75em"> <%= @user.lock ? "[LOCKED]" : "" %></div><br/>
        <strong>Password Expiry</strong> <%= formatDate @user.expiry%><br/>
        <strong>Account Expiry</strong> <%= formatDate @user.account_expiry%><br/>
        <strong>Microposts</strong> <%= @user.microposts.count %>
        <br />
        <label>Rights</label><br>
        <%= select(@user, :role_ids, Role.all(:order=>"name ASC").collect { |x| [x.name, x.id]}, {:selected => @user.role_ids}, {:multiple => true, :disabled => true}) %>
        <br />
        <br />
        <div class='button-group'>
        <%= link_to 'Edit', edit_admin_user_path(@user), :class => 'minibutton' %>
        <%= link_to 'Users List', admin_users_path, :class => 'minibutton' %>
        </div>
      </td>
    </tr>
</table>